version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
python:
  install:
    - requirements: simulation_Rubin/ulens_lsst/docs/requirements.txt
    - method: pip
      path: simulation_Rubin/dp0_rubin/ulens_lsst
sphinx:
  configuration: simulation_Rubin/dp0_rubin/ulens_lsst/docs/conf.py
