[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ulens_lsst"
version = "1.0.0"
description = "LSST pipeline for microlensing simulations"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Karen Nowogrodzki", email = "nowo.karen@gmail.com" }
]

license = { text = "MIT" }

keywords = ["LSST", "microlensing", "astronomy", "simulation"]

dependencies = [
    "numpy>=1.23.0",
    "pandas>=1.5.0",
    "pyarrow>=7.0.0",
    "astropy>=5.0.0",
    "matplotlib>=3.5.0",
    "tqdm>=4.0.0",
    "scipy>=1.9.0",
    "photutils>=1.5.0",
    "pyLIMA",
    "requests>=2.25.0",
    "astro-datalab",
    "spherical_geometry",
    "rubin-sim>=2.3.0"
]

[project.urls]
"Documentation" = "https://ulens-lsst.readthedocs.io"
"Source" = "https://github.com/nowokaren/ulens_lsst"
"Bug Tracker" = "https://github.com/nowokaren/ulens_lsst/issues"

[project.scripts]
ulens_lsst = "ulens_lsst.run_pipeline:main"

[tool.setuptools]
packages = ["ulens_lsst"]
include-package-data = true
package-dir = { "" = "." }

[tool.setuptools.package-data]
"ulens_lsst" = ["data/chunks_TRILEGAL_Genulens/*", "config/*.yaml"]
