version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
python:
  install:
    - requirements: ulens_lsst/docs/requirements.txt
    - method: pip
      path: ulens_lsst
sphinx:
  configuration: ulens_lsst/docs/conf.py